export const ActionTypes = {
    GET_MENU: 'GET_MENU',
    INSERT_ITEM: 'INSERT_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    DELIVERY_MODAL_STATUS: 'DELIVERY_MODAL_STATUS',
    ADD_ORDER: 'ADD_ORDER',
    GET_ORDERS: 'GET_ORDERS',
    SEARCH_PARAMETERS: 'SEARCH_PARAMETERS',
    SET_FIRST_PRICE:'SET_FIRST_PRICE',
    GET_TOTAL_PRICE:'GET_TOTAL_PRICE',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    ADD_CURRENT_ITEM:'ADD_CURRENT_ITEM'

}
