export const ActionTypes = {
    GET_MENU: 'GET_MENU',
    INSERT_ITEM: 'INSERT_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    DELIVERY_MODAL_STATUS: 'DELIVERY_MODAL_STATUS',
    ADD_ORDER: 'ADD_ORDER',
    GET_ORDERS: 'GET_ORDERS'

}
